### ISSUE TITLE
IMAP: ignoring bad response, THROW: com.sun.mail.iap.ParsingException: error in FETCH parsing, unrecognized item at index

### ISSUE THREAD

**Issue by beangou** [eclipse-ee4j/javamail#351]
When I parse a mail's body with javax.mail.internet.MimeBodyPart.getContent() method, I used Imap protocol, a ParsingException throwed like the title described. Error details are below. However I use Pop3, I can get the text of the mail. Why?  javax.mail version is 1.6.2.

this is my method.

```javascript
public static void getMailTextContent(Part part, StringBuffer text, StringBuffer textPlain, StringBuffer textHtml) throws Exception {
    boolean isContainTextAttach = part.getContentType().indexOf("name") > 0;
    if (part.isMimeType("text/*") && !isContainTextAttach) {
        String content = "";
        try{
            content = part.getContent().toString();
        }catch(UnsupportedEncodingException uex){
            logger.error("UnsupportedEncodingException,msg={}", uex.getMessage(), uex);
            InputStream is = part.getInputStream();
            content = convertIS2String(is);
        }catch (IOException ioe) {
            logger.error("IOException", ioe);
            if (!ioe.getMessage().contains("No content")) {
                throw ioe;
            }
        }
        text.append(content);
        if (part.isMimeType("text/plain")) {
            textPlain.append(content);
        }
        if (part.isMimeType("text/html")) {
            textHtml.append(content);
        }
    } else if (part.isMimeType("message/rfc822")) {
        getMailTextContent((Part) part.getContent(), text, textPlain, textHtml);
    } else if (part.isMimeType("multipart/*")) {
        Multipart multipart = (Multipart) part.getContent();
        int partCount = multipart.getCount();
        for (int i = 0; i < partCount; i++) {
            BodyPart bodyPart = multipart.getBodyPart(i);
            try {
                getMailTextContent(bodyPart, text, textPlain, textHtml);
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }
}
```
this is the debug info.

`com.sun.mail.iap.ParsingException: error in FETCH parsing, unrecognized item at index 16416, starts with "30 OK FETCH Complete..."
	at com.sun.mail.imap.protocol.FetchResponse.parse(FetchResponse.java:229)
	at com.sun.mail.imap.protocol.FetchResponse.<init>(FetchResponse.java:96)
	at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(IMAPProtocol.java:414)
	at com.sun.mail.iap.Protocol.command(Protocol.java:395)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:2158)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetch(IMAPProtocol.java:2150)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchSectionBody(IMAPProtocol.java:1862)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBody(IMAPProtocol.java:1845)
	at com.sun.mail.imap.protocol.IMAPProtocol.fetchBody(IMAPProtocol.java:1834)
	at com.sun.mail.imap.IMAPInputStream.fill(IMAPInputStream.java:157)
	at com.sun.mail.imap.IMAPInputStream.read(IMAPInputStream.java:198)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:139)
	at com.sun.mail.util.QPDecoderStream.read(QPDecoderStream.java:87)
	at com.sun.mail.util.QPDecoderStream.read(QPDecoderStream.java:167)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at com.sun.mail.handlers.text_plain.getContent(text_plain.java:101)
	at javax.activation.DataSourceDataContentHandler.getContent(DataHandler.java:795)
	at javax.activation.DataHandler.getContent(DataHandler.java:542)
	at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:683)`

**Comment by bshannon** [comment]
Well, you've excerpted all the detail that would show exactly what's going wrong.
It looks like the server is not sending exactly 16384 bytes of data for the body of
the message, which is causing JavaMail to interpret the FETCH Completed response
as part of the previous FETCH response.

Please report this bug to the owners of 263.net.  Include all the detail that you excerpted above.

You might be able to work around this server bug by setting the [mail.imap.partialfetch](https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html#mail.imap.partialfetch)
property to false.

**Comment by bshannon** [comment]
I'm glad the workaround works.  Please don't forget to report the bug to the server vendor so they can fix the bug at the source.  Thanks.

**Comment by beangou** [comment]
> I'm glad the workaround works. Please don't forget to report the bug to the server vendor so they can fix the bug at the source. Thanks.

ok
